name: Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "github-actions-project-packages"
  EB_APPLICATION_NAME: "DevOpsNodeJSProject"
  EB_ENVIRONMENT_NAME: "Devopsnodejsproject-env"
  DEPLOY_PACKAGE_NAME: "node_js_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-west-2"

on:
  push:
    branches:
      - main

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
     - name: Clone Repository
       uses: actions/checkout@v2

     - name: Create zip deployment package 
       run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
     - name: AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
         aws-region: ${{ env.AWS_REGION_NAME }}

     - name: Copy Deployment package to S3 bucket
       run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3//${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

     - name: Success message if ok
       run: echo "CI pipeline part finished successfully!"


     



